#!/usr/bin/env node
const fs = require('fs');
const file = require('file');
const path = require('path');
const { executeMe } = require('execute-me');
const { TypeScriptExporter, logger } = require('./dist/cli/exporter');

/**
 * protobuf-parser
 * Generate TypeScript interface with Protobuf.
 *
 * @version 0.1.0
 * @param {string} output - output path
 * @param {string} mode - "global": Global Definition, "module": Module Definition
 */
function tsapi(input, output = '', mode = "module") {
  if (!input) {
    logger.error('Input file is not specified.');
    process.exit(1);
  }
  const absoluteInputPath = path.resolve(input);
  const exporter = new TypeScriptExporter();
  file.walk(absoluteInputPath, (err, dirPath, dirs, files) => {
    for (const file of files) {
      // 这里限制了必须是 pb 协议，对于非pb协议需要写 pegjs 对文本进行编译
      if (!file.endsWith('.proto')) {
        continue;
      }
      exporter.handleSource(mode, file, absoluteInputPath, output, (fileName) => {
        logger.error(`Generate from ${path.relative(absoluteInputPath, fileName)}`);
        return true;
      });
    }
  });
}

executeMe(tsapi);
